### ISSUE TITLE
Need to shutdown() after flush()

### ISSUE THREAD

**Issue by olivier-fs** [jbarszczewski/rust-tokio-tutorial#1]
Nice example for people wanting to start coding tokio servers.
But I noticed the stream is not shutdown() ed after being flush() ed.

Indeed, curl signals that the connection is "reset by peer" rather than closed.
```
$ curl --version
curl 7.85.0 (x86_64-pc-cygwin) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.2) libssh2/1.10.0 nghttp2/1.50.0
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

$ curl -X POST 'http://127.0.0.1:8181/-12.98'
curl: (56) Recv failure: Connection reset by peer
```

Adding
```
stream.shutdown().await.unwrap()
```
after the flush() solves the problem.

**Comment by jbarszczewski** [comment]
Hi!
Thanks for the info. The weird thing is that I cannot reproduce your issue. The API behaves the same when using just flush(), just shutdown() or both as you suggested.
Could you share more details how you're using it?

**Comment by olivier-fs** [comment]
Hi!
I've been running your sample code unmodified in following environment :
- Windows 10
- Rust stable 1.64.0
- Cargo.toml : tokio = { version = "1.21.2", features = ["full"] }
- curl 7.86.0 (I upgraded from 7.85.0 but result is the same)

Without shutdown() i get most of the time
```shell
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
curl: (56) Recv failure: Connection reset by peer
```
and sometimes
```shell
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
curl: (56) Recv failure: Software caused connection abort
```
depending on netwok stack timings.

With shutdown() it always (ok, just 5 times in a row) works with no error because the server side explicitely notifies the client it voluntarily closes the connection  i.e. the connection close is not due to a network error.
```shell
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
{"balance": -12.98}
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
{"balance": -25.96}
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
{"balance": -38.94}
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
{"balance": -51.92}
$ curl -X POST 'http://127.0.0.1:8181/-12.98'
{"balance": -64.899994}
```
The rust / tokio TcpStream has somehow mimicked the BSD Sockets C API, and shutdown() sends a FIN TCP packet to be acknowledged by the client for a "clean" shutdown of the connection.

On same box with wget 1.21.3 instead of curl I get :

- with shutdown()
```shell
$ wget -q -O- --method POST http://127.0.0.1:8181/-12.98
{"balance": -12.98}
$ wget -q -O- --method POST http://127.0.0.1:8181/-12.98
{"balance": -25.96}
```

- without shutdown()  [Have to remove th -q to show diagnostic] [Part of the error message is in locale fr-FR ;-]
```shell
$ wget -O- --method POST http://127.0.0.1:8181/-12.98
--2022-10-31 22:06:47--  http://127.0.0.1:8181/-12.98
Connexion à 127.0.0.1:8181… connecté.
requête HTTP transmise, en attente de la réponse… Erreur de lecture (Connection reset by peer) dans les en-têtes.
Nouvel essai.

--2022-10-31 22:06:48--  (essai :  2)  http://127.0.0.1:8181/-12.98
Connexion à 127.0.0.1:8181… connecté.
requête HTTP transmise, en attente de la réponse… Erreur de lecture (Connection reset by peer) dans les en-têtes.
Nouvel essai.
...
```

Possible reasons you get a different behavior :
- Different OS ?
- Different client ?

When trying with curl/7.86.0 from another box running Arch Linux I get no error message.
With verbose flag -v there is even a line 
```
* Connection #0 to host 192.168.1.12 left intact
```
So network timings/behaviors are different...

Anyway I would advice to at least add shutdown()... It is actually the flush() that is optional, since shutdown() should wait for data to be flushed.

Hope that helps.


BTW during my testing I made a typo in curl parameters, forgetting to add /<value> to the POST.
That triggered an unwrap() panic on line
```rust
let balance_update = input.parse::<f32>().unwrap();
```
because input is empty.
Same panic would occur with non f32 parsable content.

Quick fix:
```rust
let balance_update = input.parse::<f32>().unwrap_or(0.0);
```

Not nitpicking here... just for the sake of a better example for tokio beginners to be pleasured and join the rustaceans  :-)

**Comment by jbarszczewski** [comment]
Thanks Olivier!
This is really amazing amount of knowledge :) 
I'm mostly running rust on Debian via WSL so that might be the reason for different behaviour. I will update the code to use shutdown() instead of flush() as that seems to be better approach.
As for the parameter parsing, I wanted to keep it simple and not include validation. I feel that defaulting to 0.0 might hide the issue of malformed request. Ideally that would be checked and proper response produced but that's beyond the scope of this tutorial.

**Comment by olivier-fs** [comment]
I agree : Examples must be short, and either do a complete error handling if it doesnt clobber the source, or no error handling at all.

I never use unwrap(). expect() is always better as it adds contextual error message to the panic. Never understood why unwrap() was not deprecated or removed from rust...
